#!/usr/bin/env python3
import re
import sys

def process_alloy_output():
    """Process Alloy analyzer output from stdin and generate predicate checks"""
    
    # Read all input
    input_lines = [line.strip() for line in sys.stdin if line.strip()]
    
    # Pattern to extract predicate names from "No instance of Run checkValidityFuzzedInvX found"
    pattern = r'No instance of Run checkValidity(FuzzedInv\d+) found'
    
    # Extract all fuzzed predicate names
    fuzzed_predicates = []
    for line in input_lines:
        match = re.search(pattern, line)
        if match:
            # Extract just the predicate name (e.g., "fuzzedInv1" from "FuzzedInv1")
            full_name = match.group(1)
            # Convert first letter to lowercase (FuzzedInv -> fuzzedInv)
            pred_name = full_name[0].lower() + full_name[1:]
            fuzzed_predicates.append(pred_name)
    
    if not fuzzed_predicates:
        print("No 'No instance' errors found in the input!")
        return
    
    print(f"Found {len(fuzzed_predicates)} fuzzed predicates with 'No instance' errors")
    
    # Generate the three predicates
    output = []
    
    # Create the conjunction of all fuzzed predicates
    conjunction = " and ".join([f"{pred}[]" for pred in fuzzed_predicates])
    
    output.append("// Generated by process_alloy_output.py")
    output.append("// Predicates checking if groundTruth predicates are implied by unsatisfiable fuzzed predicates\n")
    
    # Predicate for groundTruth1
    output.append(f"pred checkGroundTruth1IsImpliedbyUnsatPreds[] {{")
    output.append(f"    {conjunction}")
    output.append(f"    and not groundTruth1[]")
    output.append(f"}}")
    output.append(f"\nrun checkGroundTruth1IsImpliedbyUnsatPreds")
    
    # Predicate for groundTruth2
    output.append(f"\n\npred checkGroundTruth2IsImpliedbyUnsatPreds[] {{")
    output.append(f"    {conjunction}")
    output.append(f"    and not groundTruth2[]")
    output.append(f"}}")
    output.append(f"\nrun checkGroundTruth2IsImpliedbyUnsatPreds")

    # Predicate for groundTruth3
    output.append(f"\n\npred checkGroundTruth3IsImpliedbyUnsatPreds[] {{")
    output.append(f"    {conjunction}")
    output.append(f"    and not groundTruth3[]")
    output.append(f"}}")
    output.append(f"\nrun checkGroundTruth3IsImpliedbyUnsatPreds")

    # Predicate for groundTruth4
    output.append(f"\n\npred checkGroundTruth4IsImpliedbyUnsatPreds[] {{")
    output.append(f"    {conjunction}")
    output.append(f"    and not groundTruth4[]")
    output.append(f"}}")
    output.append(f"\nrun checkGroundTruth4IsImpliedbyUnsatPreds")

    # Predicate for groundTruth5
    output.append(f"\n\npred checkGroundTruth5IsImpliedbyUnsatPreds[] {{")
    output.append(f"    {conjunction}")
    output.append(f"    and not groundTruth5[]")
    output.append(f"}}")
    output.append(f"\nrun checkGroundTruth5IsImpliedbyUnsatPreds")
    
    # Write to file
    with open('groundtruth-checks.als', 'w') as f:
        f.write('\n'.join(output))
    
    print(f"✓ Generated 2 predicates checking groundTruth implications to groundtruth-checks.als")
    print(f"  Using {len(fuzzed_predicates)} fuzzed predicates")
    print(f"  Sample: {fuzzed_predicates[0]}, {fuzzed_predicates[1]}, ..., {fuzzed_predicates[-1]}")

def main():
    """Main function to process input"""
    try:
        process_alloy_output()
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
